name: Release

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: "Dry run?"
        required: true
        default: true
        type: boolean

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set Node.js 19.x
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 19.x
          cache: yarn

      - name: Install dependencies
        run: yarn ci

      - name: Run all
        run: yarn all

      - name: Check Dry Run setting
        run: |
          if [[ "${{ github.event.inputs.dry-run }}" == "true" ]]; then
            echo "DRY_RUN=true" >> $GITHUB_ENV
          else
            echo "DRY_RUN=false" >> $GITHUB_ENV
          fi

      - name: Release
        run: yarn release --dry-run ${{ env.DRY_RUN }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
